---
driver:
  name: hyperv
  vm_switch: DefaultExternalSwitch
  # parent_vhd_folder: D:\VirtualMachines\Windows Server 2016 DataCenter Nano VHD
  # parent_vhd_name: NanoServerDataCenter.vhd
  # username: administrator
  # password: admin777!
  parent_vhd_folder: D:\VirtualMachines
  parent_vhd_name: packer-virtualbox-iso-1458688988.vhd
  username: vagrant
  password: vagrant
  memory_startup_bytes: 1073741824

transport:
  name: winrm
  # username: administrator
  # password: admin777!
  username: vagrant
  password: vagrant
  elevated: true
  elevated_username: vagrant
  elevated_password: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: pester

  
platforms:
  - name: w2008r2
    os_type: windows
    shell_type: powershell
    # driver_config:
    #   user_data: test/support/scripts/userdata.txt

suites:
  - name: default
    run_list:
      - recipe[acme_win_web::default]
    # verifier:
    #   inspec_tests:
    #     - test/smoke/default
    # attributes:
